version: '3.1'

services:
  wordpress:
      image: wordpress:apache
      container_name: ${WP_CONTAINER}
      links:
       - mariadb:mysql
      environment:
       - WORDPRESS_DB_PASSWORD=${DB_PASS}
       - WORDPRESS_DB_USER=root
       - WORDPRESS_DB_HOST=mariadb
       - WORDPRESS_DB_NAME=${DB_NAME}
      ports:
       - 80:80
      volumes:
       - ./Themes/:/var/www/html/wp-content/themes/
       - ./Plugins/:/var/www/html/wp-content/plugins/
       - ./Uploads/:/var/www/html/wp-content/uploads/
      depends_on:
       - mariadb
      networks:
       - wordpress

  mariadb:
      image: mariadb
      container_name: ${DB_CONTAINER}
      environment:
       - MARIADB_ROOT_PASSWORD=${DB_PASS}
       - MARIADB_DATABASE=${DB_NAME}
      volumes:
       - ./DatabaseData:/var/lib/mysql
      networks:
       - wordpress

networks:
    wordpress:
      name: wordpress_net